services:
    api:
        build:
            context: .
            dockerfile: dockerfile.api
        image: ats-api
        ports:
            - '5000:5000'
        networks:
            - ats-network
        develop:
            watch:
                - action: rebuild
                  path: ./backend
                  target: /app
                  ignore:
                    - "**/__pycache__/"
                    - "**/*.pyc"
    client:
        build:
            context: .
            dockerfile: dockerfile.client
        image: ats-client
        ports:
            - '3000:3000'
        networks:
            - ats-network
        develop:
            watch:
                - action: sync
                  path: ./frontend/src
                  target: /app/src
                - action: rebuild
                  path: ./frontend/package.json
        environment:
            - REACT_APP_GEMINI_API_KEY=${GEMINI_API_KEY}

networks:
    ats-network:
        driver: bridge
