FROM python:3.9.7

RUN apt-get update && apt-get install -y build-essential cmake

WORKDIR /app

COPY . .
RUN pip3 install -r requirements.txt
EXPOSE 5000

ENV FLASK_APP=app.py
CMD ["flask", "run", "--host=0.0.0.0"]
