name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install essential dependencies
      run: |
        python -m pip install --upgrade pip
        # Install only the packages we actually use
        pip install pytest==7.4.4
        pip install requests==2.31.0
        pip install openai==1.12.0
        pip install python-dotenv==1.0.0

    - name: Verify installations
      run: |
        echo "Installed packages:"
        pip list

    - name: Run tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python -m pytest tests/test1.py -v -s