name: Python Tests

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install pip
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install dependencies
      run: |
        python -m pip install pytest==7.4.4
        python -m pip install pytest-cov==4.1.0
        python -m pip install python-dotenv==1.0.0
        python -m pip install requests==2.31.0
        python -m pip install openai==1.12.0
        if [ -f requirements.txt ]; then
          while read requirement; do
            if [[ $requirement != "#"* ]] && [[ -n $requirement ]]; then
              python -m pip install "$requirement"
            fi
          done < requirements.txt
        fi

    - name: List installed packages
      run: |
        pip list

    - name: Run tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python -m pytest tests/test1.py -v -s
