name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu for better compatibility
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Use the latest Python 3.x version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade pytest

      - name: Run tests
        run: |
          python3 ../../backend/test_app.py